# MetalLB L2 Mode Post-Installation Configuration
# Save as: metallb-l2-config.yaml
# Apply AFTER MetalLB installation

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb
spec:
  # Replace with your actual IP range
  addresses:
  - 192.168.29.240-192.168.29.250
  autoAssign: true
  avoidBuggyIPs: true

---
# L2Advertisement for Layer 2 mode
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-l2-adv
  namespace: metallb
spec:
  ipAddressPools:
  - default-pool
  # Optional: restrict to specific nodes
  # nodeSelectors:
  # - matchLabels:
  #     kubernetes.io/hostname: worker-1